//* FAÇA UM PROGRAMA COM UMA CLASSE PESSOA COM NOME E CPF, SEUS GETTERS E SETTERS. 
//* DEPOIS UMA CLASSE PROFESSOR SUBCLASSE DE PESSOA COM SALÁRIO, SEUS GETTERS E SETTERS. 
//* A CLASSE PROFESSOR DEVE TER 2 MÉTODOS CONSTRUTORES, UM QUE NÃO RECEBE PARÂMETROS E UMA QUE RECEBE NOME, CPF E SALÁRIO.
//* DEPOIS CRIE UMA PESSOA COM NOME E CPF E CRIE UM FUNCIONÁRIO COM NOME, CPF E SALÁRIO.

//! OBS.: FAÇA PRIMEIRO UM DIAGRAMA UML, DEPOIS CODIFIQUE O PROGRAMA."

#include <iostream>
using namespace std;